version: "3"

services: 
    mysql:
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - mysql_data:/var/lib/mysql
        ports: 
            - 9998:3306
volumes:
    mysql_data: